# Generated by Django 4.2.30 on 2026-05-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interno', models.CharField(help_text='Ej: Lista Toyota Mayo', max_length=150)),
                ('slug_url', models.SlugField(help_text='Ej: precios-toyota (Se usa para la URL)', max_length=150, unique=True)),
                ('url_drive_destino', models.URLField(help_text='El enlace real de Google Drive', max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogos', to='usuarios.vendedor')),
            ],
        ),
    ]
