# Generated by Django 4.2.30 on 2026-05-12 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('permite_registro', models.BooleanField(default=True, help_text='¿Se puede usar este código en la pantalla principal para crear una cuenta nueva?')),
                ('dias_gratis_otorgados', models.PositiveIntegerField(default=0, help_text='Días de prueba gratuita que suma al registrarse.')),
                ('porcentaje_descuento', models.PositiveIntegerField(default=0, help_text='Descuento (Ej: 20 para 20%) aplicable en el registro o al reportar un pago.')),
                ('usos_maximos', models.PositiveIntegerField(default=1, help_text='Pon 0 para usos ilimitados')),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, help_text='Ej: Código para campaña de Instagram Junio')),
            ],
        ),
        migrations.AddField(
            model_name='vendedor',
            name='publicidad_activada',
            field=models.BooleanField(default=False, help_text="Si está activo, muestra 'Powered by' en la pantalla puente a cambio de descuento."),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='telefono_whatsapp',
            field=models.CharField(default='0000000000', help_text='Ej: +584141234567', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='codigo_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.codigopromocional'),
        ),
    ]
