# Generated by Django 4.2.30 on 2026-05-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('marca_modelo_aprox', models.CharField(blank=True, max_length=150, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, null=True)),
                ('es_iphone', models.BooleanField(default=False)),
                ('fecha_primera_visita', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_entrada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_publica', models.GenericIPAddressField(blank=True, null=True)),
                ('proveedor_internet_isp', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_aprox', models.CharField(blank=True, max_length=150, null=True)),
                ('metadata_extra', models.JSONField(blank=True, default=dict)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='catalogos.catalogo')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_visitas', to='tracking.dispositivo')),
            ],
        ),
    ]
