# Generated by Django 4.2.30 on 2026-05-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='user_agent_raw',
            field=models.TextField(blank=True, help_text='Cadena completa del navegador', null=True),
        ),
    ]
