# Generated by Django 4.2.30 on 2026-05-13 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_codigopromocional_vendedor_publicidad_activada_and_more'),
        ('tracking', '0002_visita_user_agent_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='vendedor_asociado',
            field=models.ForeignKey(blank=True, help_text='Si este dispositivo se registra como cliente nuestro, lo vinculamos aquí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_conocidos', to='usuarios.vendedor'),
        ),
    ]
